image: docker:stable
services:
  - docker:dind

stages:
  - Build image

docker build:
  stage: Build image
  script:
  - docker info
  - docker build --build-arg branch=$CI_COMMIT_REF_NAME -t edcd/coriolis:$CI_COMMIT_REF_NAME .
  - echo "$REGISTRY_PASSWORD" | docker login --username "$REGISTRY_USER" --password-stdin
  - docker push edcd/coriolis:$CI_COMMIT_REF_NAME
