version: '3.6'

services:
  master:
    image: edcd/coriolis:master
    build:
      dockerfile: Dockerfile
      context: .
      args:
        branch: master
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:coriolis.io,coriolis.edcd.io"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

  develop:
    image: edcd/coriolis:develop
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        branch: develop
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:beta.coriolis.io,beta.coriolis.edcd.io"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

networks:
  web:
    external: true
